### PR TITLE
Fix OnChange Event Invocation

### LINKED ISSUE #1997: onChange event not called when adding new block
When I create a new element, e.g. a delimiter, and instantly store my content, the new element is not stored because the `onChange` event is not triggered. But when creating a new element and changing content (active keyup), the element gets stored because the `onChange` is triggered.

Expected behavior: `onChange` should be called after adding a new element.

Screenshots: https://www.loom.com/share/5bba14a6eb844bfdae677b47ee5e2553

Device, Browser, OS: macOS Safari

Editor.js version: 2.23.2

### PR DESCRIPTION
**Pull request by robonetphy**
resolve #1997

### CODE REVIEW

**Review by ilyamore88 — APPROVED** [review]

File: src/components/modules/saver.ts [hunk 1]
```diff
@@ -28,15 +28,11 @@ export default class Saver extends Module {
...
    */
   public async save(): Promise<OutputData> {
-    const { BlockManager, Tools, ModificationsObserver } = this.Editor;
+    const { BlockManager, Tools } = this.Editor;
     const blocks = BlockManager.blocks,
         chainData = [];
 
     try {
-      /**
-       * Disable onChange callback on save to not to spam those events
```
Comment (neSpecc) [inline src/components/modules/saver.ts:37]: Do you mean that this problem is not relevant for now? Why?

Comment (neSpecc) [reply src/components/modules/saver.ts:37]: And how is it related to the Delimiter tool?

Comment (robonetphy) [reply src/components/modules/saver.ts:37]: Its not related to the delimiter because when we call `save` function inside OnChange event it disables upcomming onchange events by calling `modificationObserver.disable()`.

Comment (robonetphy) [reply src/components/modules/saver.ts:37]: @neSpecc do you have any test cases such that I can check because I don't know if it occurs or not

> Do you mean that this problem is not relevant for now? Why?

Comment (neSpecc) [reply src/components/modules/saver.ts:37]: I've dug in git history a little bit, but could not find the reason why that disable/enable logic was added. So I think, it could be removed.

File: docs/CHANGELOG.md [hunk 2]
```diff
@@ -10,21 +14,21 @@
...
-- `Improvement` — *Dev Example Page* — The 'dark' theme added. Now we can code at night more comfortably.
-- `Improvement` — *Rectangle Selection* — paint optimized
-- `Fix` — *Rectangle Selection* — the first click after RS was not clear selection state. Now does.
-- `Improvement` — *Blocks API* — toolbar moving logic removed from `blocks.move()` and `blocks.swap()` methods. Instead, you should use Toolbar API (it was used by MoveUp and MoveDown tunes, they were updated).
-- `New` — *Blocks API* — The `getBlockIndex()` method added
-- `New` — *Blocks API* — the `insert()` method now has the `replace: boolean` parameter
-- `New` — *Blocks API* —  the `insert()` method now returns the inserted `Block API`
-- `New` — *Listeners API* — the `on()` method now returns the listener id.
-- `New` — *Listeners API* — the new `offById()` method added
+- `Improvement` — _EditorConfig_ — The `onChange` callback now accepts two arguments: EditorJS API and the CustomEvent with `type` and `detail` allowing to determine what happened with a Block
```
Comment (neSpecc) [inline docs/CHANGELOG.md]: why the whole changelog has changed?

Comment (robonetphy) [reply docs/CHANGELOG.md]: Ohh sorry it's due to my editor configuration

**Review by neSpecc — APPROVED** [review]

**Review by gohabereg — APPROVED** [review]

**Comment by robonetphy** [comment]
@gohabereg I checked `tests` with `next` branch is failing.
onChange callback -- should fire onChange callback on block insertion with save inside onChange (failed)

**Review by ilyamore88 — APPROVED** [review]

**Review by gohabereg — APPROVED** [review]

**Comment by drakst** [comment]
Hi. Instead of onChange event you can try to connect MutationObserver to editor ad watch for updates.

Config of observe can be something like: {
	attributes: false,
	childList: true,
	subtree: true,
	characterData: true
}

Im using this config on vue project for change v-model value
