### PR TITLE
fix(scroll): acidental scroll to top on iOS devices

### LINKED ISSUE #2261: Scroll to top when popover_overlay clicked on iPhone Safari
1. The browser scrolls to the top and scrolls back to where I was whenever I touch popover_overlay to close the popover.
2. Touching `+` button to add another block does not set caret to the newly created block.

First bug:
1. On my iphone 14 pro, I visited https://editorjs.io/
3. I clicked **Play With Demo** to try the editor on mobile.
4. typed some texts and touched **Block Tunes** button.
5. The popover showed up, and I touched the overlay to close the popover.
6. The browser scrolled to the top and scrolled back to where I was

Second bug:
1. write some text
2. touch `+` button and choose **Heading**
3. check if the caret is showing on a new block.
4. I had to touch the new block **twice** in order to get focus.

Expected behavior:

Screenshots:

https://user-images.githubusercontent.com/108341074/216000617-9fba71de-ee9b-4e83-b276-f642820e5c71.MP4

Device, Browser, OS: iPhone 14 Pro, Safari

Editor.js version: I faced this issue on 2023/02/01 GMT. So the version should be `2.26.5`?

Plugins you use with their versions:

### LINKED ISSUE #2689: Scrolls to the top of the page when focused on some select element
Describe a bug.

Steps to reproduce:
1. add **SelectElement** (following html) to `/index.html`
2. start development server with `yarn && yarn dev`
3. access http://localhost:3303 on iOS 16.2 - safari
4. scroll to the select element (note: do not touch any element other than select)

**SelectElement**

```html
<label for="pet-select">Choose a pet:</label>
<select name="pets" id="pet-select">
  <option value="">--Please choose an option--</option>
  <option value="dog">Dog</option>
  <option value="cat">Cat</option>
  <option value="hamster">Hamster</option>
  <option value="parrot">Parrot</option>
  <option value="spider">Spider</option>
  <option value="goldfish">Goldfish</option>
</select>
```

Expected behavior:
open select menu

Screenshots:

https://github.com/codex-team/editor.js/assets/38370581/cc8d93f6-74be-4c96-b8b7-f9ad3dcd00c8

Device, Browser, OS:

iPhone 13, safari, 16.2

Editor.js version: [next](https://github.com/codex-team/editor.js/tree/next)

Plugins you use with their versions:

### PR DESCRIPTION
**Pull request by neSpecc**
## Problem 

When you type something on iOS, page will be scrolled to top.

https://github.com/codex-team/editor.js/assets/3684889/6399278d-0ab4-4592-bc89-df60b158af55

Fixes #2689
Possible fixes #2261

## Cause

Due to lack of the "strict" mode in the `tsconfig` there was a missed problem in the "scroll-locker.ts" class.

The iOS-specific method `unlockHard()` (called from the Popover' `hide()` which is being called every keydown) checks for `null`, but `this.scrollPosition` was `undefined` initially 

```ts
  /**
   * Unlocks hard scroll lock
   */
  private unlockHard(): void {
    document.body.classList.remove(ScrollLocker.CSS.scrollLockedHard);
    if (this.scrollPosition !== null) { 
      window.scrollTo(0, this.scrollPosition);
    }
    this.scrollPosition = null;
  }
```

## Solution

1. I initialized `this.scrollPosition` with `null` explicitly.
2. Additionally, I updated the PopoverMobile's `hide()` method. Now it won't trigger any logic if popover is already hidden (to prevent possible layout caused by CSS classes adding)

### CODE REVIEW

File: src/components/utils/popover/popover-mobile.ts [hunk 1]
```diff
@@ -64,6 +64,12 @@ export class PopoverMobile extends PopoverAbstract<PopoverMobileNodes> {
    * Closes popover
    */
   public hide(): void {
+    const isAlreadyHidden = this.nodes.overlay.classList.contains(css.overlayHidden);
```
Comment (TatianaFomina) [inline src/components/utils/popover/popover-mobile.ts]: maybe store isOpen flag in a variable? Not sure it's a good idea to check dom

Comment (neSpecc) [reply src/components/utils/popover/popover-mobile.ts]: why not? it does not lead layout

**Review by TatianaFomina — APPROVED** [review]

**Review by gohabereg — APPROVED** [review]
