### PR TITLE
Fix copy in FireFox

### LINKED ISSUE #1625: [Bug] Unable to copy blocks
When I'm in block selection mode, I'm unable to copy the block content

Steps to reproduce:
1. Go to https://editorjs.io/
2. Select several block
3. Copy the blocks, with either ctrl + C or right-click / copy
4. Go to a text editor, try to paste.
5. The blocks have not been copied

Expected behavior: The block content should have been copied

Screenshots:
image

Device, Browser, OS: Firefox developer 88.0b6 on Windows 10 20H2

Editor.js version: The one live at editorjs.io

### PR DESCRIPTION
**Pull request by gohabereg**
closes #1625

### CODE REVIEW

**Comment by neSpecc** [comment]
Check this PR, please https://github.com/codex-team/editor.js/pull/1485. Is that problem still actual?

**Comment by gohabereg** [comment]
@neSpecc I've wrapped blocks deletion into then statement, PR above is not actual anymore

UPD: I see it's merged, so changes are reflected in my PR

**Review by neSpecc — APPROVED** [review]

File: src/components/modules/blockEvents.ts [hunk 1]
```diff
@@ -167,37 +167,37 @@ export default class BlockEvents extends Module {
...
     if (!BlockSelection.anyBlockSelected) {
       return;
     }
 
-    await BlockSelection.copySelectedBlocks(event);
+    BlockSelection.copySelectedBlocks(event).then(() => {
+      const selectionPositionIndex = BlockManager.removeSelectedBlocks();
 
-    const selectionPositionIndex = BlockManager.removeSelectedBlocks();
+      Caret.setToBlock(BlockManager.insertDefaultBlockAtIndex(selectionPositionIndex, true), Caret.positions.START);
```
Comment (khaydarov) [inline src/components/modules/blockEvents.ts]: I think for readability it will be better

```js
const insertedBlock = BlockManager.insertDefaultBlockAtIndex(selectionPositionIndex, true);

Caret.setToBlock(insertedBlock, Caret.positions.START);
```

**Review by khaydarov — APPROVED** [review]
