### PR TITLE
[Fix] Stop jumping to block start on toolbox close

### LINKED ISSUE #2045: [Bug] Keyboard selection by word doesn't work when selecting from right to left
Describe a bug.

Steps to reproduce:
1. Go to https://editorjs.io
2. Click in the middle of any paragraph 
3. Try to select several words via keyboard from right to left (on MacOS Opt + Shift + Arrow left)

Expected behaviour:
Words should be selected

Actual behaviour:
After selecting the second word selection is lost and cursor jumps to the beginning of the paragraph

Device, Browser, OS:
Chrome, MacOS

Editor.js version:
2.24.2

### PR DESCRIPTION
**Pull request by TatianaFomina**
Fixes problem with text selection from right to left. Moving caret to block start on toolbox close was causing the problem. 

Resolves https://github.com/codex-team/editor.js/issues/2045

### CODE REVIEW

File: src/components/modules/toolbar/index.ts [hunk 1]
```diff
@@ -167,7 +167,6 @@ export default class Toolbar extends Module<ToolbarNodes> {
       opened: this.toolboxInstance.opened,
       close: (): void => {
         this.toolboxInstance.close();
-        this.Editor.Caret.setToBlock(this.Editor.BlockManager.currentBlock);
```
Comment (TatianaFomina) [inline src/components/modules/toolbar/index.ts:170]: @neSpecc 
didn't get why this line is needed, so removed it. If it is needed, it can be executed on condition or moved to some other place

Comment (neSpecc) [reply src/components/modules/toolbar/index.ts:170]: Try this:

1) Place the caret to the empty block
2) Press Tab to open the Toolbox
3) Press Esc to close the Toolbox

The Caret should return to the empty block. In case of removing this line that wouldn't happenn.

Comment (TatianaFomina) [reply src/components/modules/toolbar/index.ts:170]: Ok, moved this line to function called on esc press

**Review by neSpecc — APPROVED** [review]

**Review by gohabereg — APPROVED** [review]

**Review by ilyamore88 — APPROVED** [review]
