### PR TITLE
fix issue #2523

### LINKED ISSUE #2523: Bug: editor.onChange is not triggered in case of removing the whole text inside block, if the contenteditable element is not the root node of a block
https://github.com/codex-team/editor.js/blob/ee188bfe5de9c99592396250f6fce90f63b2957e/src/components/utils/mutations.ts#L15 - 
this check won't help if the change happened within some descendant of the 'element'.

For example, if we remove the text inside one of the 'li' items of '@editorjs/nested-list' block, onChange won't be triggered.

### PR DESCRIPTION
**Pull request by VikhorKonstantin**
fix #2523:

fixing the following function: https://github.com/codex-team/editor.js/blob/ee188bfe5de9c99592396250f6fce90f63b2957e/src/components/utils/mutations.ts#L7 
Made this function return `true` if the whole text node is removed inside of some descendant of the passed `element`.

This PR addresses the issue where the onChange is not triggered if the text inside one of the 'li' items of the '@editorjs/nested-list' block is removed.

### CODE REVIEW

File: src/components/utils/mutations.ts [hunk 1]
```diff
@@ -7,29 +7,20 @@
 export function isMutationBelongsToElement(mutationRecord: MutationRecord, element: Element): boolean {
   const { type, target, addedNodes, removedNodes } = mutationRecord;
 
-  /**
-   * In case of removing the whole text in element, mutation type will be 'childList',
-   * 'removedNodes' will contain text node that is not existed anymore, so we can't check it with 'contains' method
-   * But Target will be the element itself, so we can detect it.
-   */
```
Comment (neSpecc) [inline src/components/utils/mutations.ts]: why comments are removed?

**Review by neSpecc — CHANGES_REQUESTED** [review]

File: src/components/utils/mutations.ts
Comment (neSpecc) [inline src/components/utils/mutations.ts:1]: add corresponding tests please

File: src/components/utils/mutations.ts (hunk 1 above)
Comment (VikhorKonstantin) [reply src/components/utils/mutations.ts]: @neSpecc Hi, I've restructured the code a little bit and replaced the part this comment was addressed to.

File: src/components/utils/mutations.ts
Comment (VikhorKonstantin) [reply src/components/utils/mutations.ts:1]: Done

File: src/components/utils/mutations.ts (hunk 1 above)
Comment (neSpecc) [reply src/components/utils/mutations.ts]: So you need to write the new comments explaining all logical parts.

P.S. Please, do not resolve other people's comments. Reply instead.

File: test/cypress/tests/onchange.cy.ts [hunk 2]
```diff
@@ -1,5 +1,6 @@
 import Header from '@editorjs/header';
 import Code from '@editorjs/code';
+import Checklist from '@editorjs/checklist';
```
Comment (neSpecc) [inline test/cypress/tests/onchange.cy.ts]: Is this dependency really required? It would be better to use mock instead, check `fixtures/tools/ToolMock.ts`

Comment (VikhorKonstantin) [reply test/cypress/tests/onchange.cy.ts]: Replaced with a ToolMock

File: src/components/utils/mutations.ts (hunk 1 above)
Comment (VikhorKonstantin) [reply src/components/utils/mutations.ts]: Added some comments

File: src/components/utils/mutations.ts [hunk 3]
```diff
@@ -7,29 +7,23 @@
...
-  if (target === element) {
+  if (element.contains(target)) {
     return true;
   }
 
   /**
-   * Check typing and attributes changes
+   * In case of removing/adding the element itself, mutation type will be 'childList' and 'removedNodes'/'addedNodes' will contain the element.
    */
-  if (['characterData', 'attributes'].includes(type)) {
```
Comment (neSpecc) [inline src/components/utils/mutations.ts:22]: Am I understanding it right that `characterData` and `attributes` mutations covered by `element.contains(target)` statement? Docs are not clear

Comment (VikhorKonstantin) [reply src/components/utils/mutations.ts:22]: Yes, `element.contains(target)` covers all mutations happened to the element or it's descendants with the only one exception - removing/adding the element itself, because in this case target will be the element's parent and the element itself would be inside 'removedNodes'/'addedNodes'.

Comment (VikhorKonstantin) [reply src/components/utils/mutations.ts:22]: Added more explanation + fixed formatting.

**Review by neSpecc — COMMENTED** [review]
Seems ok, please, drop a line at the `docs/CHANGELOG.md` under the new 2.30.0 section

**Comment by VikhorKonstantin** [comment]
> Seems ok, please, drop a line at the `docs/CHANGELOG.md` under the new 2.30.0 section

Done

**Review by neSpecc — APPROVED** [review]

**Review by gohabereg — APPROVED** [review]
