### PR TITLE
fix: scroll up offset for blocks above viewport

### LINKED ISSUE #2297: Move up tune scrolls to top when previous block is above and outside view port
I've noticed that when i move up some blocks the browsers scrolls too far, all the way to the top of the page.

Steps to reproduce:
1. Add a few blocks to the editor
2. Scroll down until the previous block (the block before the selected block) is above and outside the viewport
3. Tap Move Up tune.
4. Observe that it moves to the top of the page

Expected behavior:
I expected the window to scroll until the block, that is selected, is visible

Screenshots: 

https://user-images.githubusercontent.com/23644557/224296305-c86e6394-2cb1-4819-95af-4f6d5680dd40.mov

(Apologies for the lag i was debugging in chrome dev console)

Device, Browser, OS: iOS Chrome, iOS Safari & Mac OS Chrome.

Editor.js version: 2.26.4

Plugins you use with their versions: Designed a custom plugin that support multiple image upload.

More info:

I've identified the issue to be this line of code: https://github.com/codex-team/editor.js/blob/master/src/components/block-tunes/block-tune-move-up.ts#L105

scrollUpOffset is too large ofa number because it calculated using the the innerHeight to determine the offset then using scrollBy. In my case the offset value comes out to be 700-800px which is why it scrolls to the top.

I suggest changing the line of code to the following:

```
scrollUpOffset = Math.abs(currentBlockCoords.top) + previousBlockCoords.height;
```

In my debugging i find this to work as expected, it scrolls until the block is at the top of the screen. 

Created pr to fix this: https://github.com/codex-team/editor.js/pull/2298

### PR DESCRIPTION
**Pull request by kiorq**
Fixes issue where Move Up tune would scroll to top of page when the previous block is above viewport.

resolves #2297

### CODE REVIEW

File: src/components/block-tunes/block-tune-move-up.ts [hunk 1]
```diff
@@ -3,9 +3,9 @@
  * @classdesc Editor's default tune that moves up selected block
  * @copyright <CodeX Team> 2018
  */
-import { API, BlockTune } from '../../../types';
-import { IconChevronUp } from '@codexteam/icons';
-import { TunesMenuConfig } from '../../../types/tools';
+import { API, BlockTune } from "../../../types";
```
Comment (neSpecc) [inline src/components/block-tunes/block-tune-move-up.ts]: Thanks for the PR, please follow our Code Style

Comment (kiorq) [reply src/components/block-tunes/block-tune-move-up.ts]: Oops, prettier kicked in. I Resolved it. Thanks.

**Review by TatianaFomina — APPROVED** [review]

**Review by neSpecc — APPROVED** [review]
Please, add a change log

**Comment by kiorq** [comment]
Thanks a ton for the approvals. Question: How soon could we expect v2.27.0 to be released?

**Review by ilyamore88 — APPROVED** [review]

**Comment by ilyamore88** [comment]
Hi, @kiorq. We're working on the next release. If you need this fix ASAP, it's available in version `2.27.0-rc.2`.

**Comment by kiorq** [comment]
Awesome, we will use the pre release until the 2.27.0 is ready. Thanks a ton.
